services:
  api-nairim:
    container_name: nairim-api
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql://nairim:nairim@postgres:5432/nairim_db?schema=public

  postgres:
    image: postgres:16-alpine
    container_name: nairim-postgres
    restart: always
    environment:
      POSTGRES_USER: nairim
      POSTGRES_PASSWORD: nairim
      POSTGRES_DB: nairim_db
    ports:
      - "5432:5432"
    volumes:
      - ./uploads:/app/uploads
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: