services:
  api-nairim:
    container_name: nairim-api
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./uploads:/app/uploads
    command: sh -c "npx prisma db push && npm run start"

  api-nairim-test:
    container_name: nairim-api-test
    build: .
    restart: always
    ports:
      - "5001:5000" 
    volumes:
      - ./uploads-test:/app/uploads

  postgres:
    image: postgres:16-alpine
    container_name: nairim-postgres
    restart: always
    environment:
      POSTGRES_USER: nairim
      POSTGRES_PASSWORD: nairim
      POSTGRES_DB: nairim_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: