import { Router } from 'express';
import agencyRoutes from './agency';
import userRoutes from './user';
import leaseRoutes from './lease';
import ownerRoutes from './owner';
import tenantRoutes from './tenant';
import propertyTypeRoutes from './property-type';
import propertyRoutes from './property';
import dashboardRoutes from "./dashboard";
import favoriteRoutes from "./favorite";
import authRoutes from "./auth";
import FinancialInstitution from "./financial-intitucion";
import FinancialCategory from "./category";
import FinancialSubCategory from "./subcategory";
import FinancialCard from "./card";
import FinancialCenter from "./center";
import FinancialSupplier from "./supplier";
import FinancialTransaction from "./transaction";

const router = Router();

router.use('/agencies', agencyRoutes);
router.use('/users', userRoutes);
router.use('/leases', leaseRoutes);
router.use('/owners', ownerRoutes);
router.use('/tenants', tenantRoutes);
router.use('/property-types', propertyTypeRoutes);
router.use('/properties', propertyRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/favorites", favoriteRoutes);
router.use("/auth", authRoutes);
router.use("/financial-institution", FinancialInstitution);
router.use("/financial-category", FinancialCategory);
router.use("/financial-subcategory", FinancialSubCategory);
router.use("/financial-card", FinancialCard);
router.use("/financial-center", FinancialCenter);
router.use("/financial-supplier", FinancialSupplier);
router.use("/financial-transaction", FinancialTransaction);

export default router;