-- AlterTable
ALTER TABLE "Lease" ALTER COLUMN "rent_amount" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "condo_fee" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "property_tax" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "extra_charges" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "commission_amount" SET DATA TYPE DECIMAL(20,2);

-- AlterTable
ALTER TABLE "PropertyValue" ALTER COLUMN "purchase_value" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "rental_value" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "condo_fee" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "property_tax" SET DATA TYPE DECIMAL(20,2);
